/**
* Generated by LEA for Arma 3
* Version: 2.0.17
* Sun Apr 13 12:08:14 CEST 2014
* Mission file name: tvt07_where-is-the-agent-4.Altis
* Mission name: tvt07_where-is-the-agent-4.Altis
* Required mods:
* + ArmA 3
* 
* Call the script: _dummy = [] execvm "lea\loadoutServer.sqf";
* 
*/

/**
* Loadout for crates
*/

  clearweaponcargoGlobal supply_basic_weapons;
  clearmagazinecargoGlobal supply_basic_weapons;
  clearitemcargoGlobal supply_basic_weapons;

  supply_basic_weapons addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo;
  clearmagazinecargoGlobal supply_ammo;
  clearitemcargoGlobal supply_ammo;

  supply_ammo addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives;
  clearmagazinecargoGlobal supply_explosives;
  clearitemcargoGlobal supply_explosives;

  supply_explosives addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives additemcargoGlobal ["FirstAidKit",1];
  supply_explosives additemcargoGlobal ["Rangefinder",1];
  supply_explosives additemcargoGlobal ["NVGoggles",1];
  supply_explosives additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers;
  clearmagazinecargoGlobal supply_launchers;
  clearitemcargoGlobal supply_launchers;

  supply_launchers addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades;
  clearmagazinecargoGlobal supply_grenades;
  clearitemcargoGlobal supply_grenades;

  supply_grenades addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons;
  clearmagazinecargoGlobal supply_special_weapons;
  clearitemcargoGlobal supply_special_weapons;

  supply_special_weapons additemcargoGlobal ["H_Bandanna_surfer",1];
  supply_special_weapons additemcargoGlobal ["H_Booniehat_dgtl",1];
  supply_special_weapons additemcargoGlobal ["H_Shemag_olive",1];
  supply_special_weapons addBackpackCargoGlobal ["B_OutdoorPack_blk",1];
  supply_special_weapons addBackpackCargoGlobal ["B_Carryall_oucamo",1];
  supply_special_weapons addItemCargoGlobal ["V_TacVest_blk",1];

  clearweaponcargoGlobal supply_basic_weapons_1;
  clearmagazinecargoGlobal supply_basic_weapons_1;
  clearitemcargoGlobal supply_basic_weapons_1;

  supply_basic_weapons_1 addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons_1 addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons_1 addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons_1 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons_1 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons_1 additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons_1 additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo_1;
  clearmagazinecargoGlobal supply_ammo_1;
  clearitemcargoGlobal supply_ammo_1;

  supply_ammo_1 addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo_1 addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives_1;
  clearmagazinecargoGlobal supply_explosives_1;
  clearitemcargoGlobal supply_explosives_1;

  supply_explosives_1 addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives_1 addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives_1 addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives_1 addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives_1 additemcargoGlobal ["FirstAidKit",1];
  supply_explosives_1 additemcargoGlobal ["Rangefinder",1];
  supply_explosives_1 additemcargoGlobal ["NVGoggles",1];
  supply_explosives_1 additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers_1;
  clearmagazinecargoGlobal supply_launchers_1;
  clearitemcargoGlobal supply_launchers_1;

  supply_launchers_1 addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers_1 addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers_1 addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades_1;
  clearmagazinecargoGlobal supply_grenades_1;
  clearitemcargoGlobal supply_grenades_1;

  supply_grenades_1 addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades_1 addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades_1 addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades_1 addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades_1 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades_1 addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades_1 addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades_1 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons_1;
  clearmagazinecargoGlobal supply_special_weapons_1;
  clearitemcargoGlobal supply_special_weapons_1;

  supply_special_weapons_1 additemcargoGlobal ["H_Bandanna_surfer",1];
  supply_special_weapons_1 additemcargoGlobal ["H_Booniehat_dgtl",1];
  supply_special_weapons_1 additemcargoGlobal ["H_Shemag_olive",1];
  supply_special_weapons_1 addBackpackCargoGlobal ["B_Carryall_oucamo",1];
  supply_special_weapons_1 addItemCargoGlobal ["V_TacVest_blk",1];

  clearweaponcargoGlobal supply_basic_weapons_2;
  clearmagazinecargoGlobal supply_basic_weapons_2;
  clearitemcargoGlobal supply_basic_weapons_2;

  supply_basic_weapons_2 addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons_2 addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons_2 addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons_2 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons_2 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons_2 additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons_2 additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo_2;
  clearmagazinecargoGlobal supply_ammo_2;
  clearitemcargoGlobal supply_ammo_2;

  supply_ammo_2 addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo_2 addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives_2;
  clearmagazinecargoGlobal supply_explosives_2;
  clearitemcargoGlobal supply_explosives_2;

  supply_explosives_2 addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives_2 addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives_2 addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives_2 addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives_2 additemcargoGlobal ["FirstAidKit",1];
  supply_explosives_2 additemcargoGlobal ["Rangefinder",1];
  supply_explosives_2 additemcargoGlobal ["NVGoggles",1];
  supply_explosives_2 additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers_2;
  clearmagazinecargoGlobal supply_launchers_2;
  clearitemcargoGlobal supply_launchers_2;

  supply_launchers_2 addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers_2 addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers_2 addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades_2;
  clearmagazinecargoGlobal supply_grenades_2;
  clearitemcargoGlobal supply_grenades_2;

  supply_grenades_2 addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades_2 addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades_2 addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades_2 addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades_2 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades_2 addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades_2 addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades_2 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons_2;
  clearmagazinecargoGlobal supply_special_weapons_2;
  clearitemcargoGlobal supply_special_weapons_2;

  supply_special_weapons_2 additemcargoGlobal ["G_Spectacles_Tinted",1];
  supply_special_weapons_2 additemcargoGlobal ["H_Bandanna_surfer",1];
  supply_special_weapons_2 additemcargoGlobal ["H_Booniehat_dgtl",1];
  supply_special_weapons_2 additemcargoGlobal ["H_Shemag_olive",1];
  supply_special_weapons_2 addBackpackCargoGlobal ["B_Carryall_oucamo",1];
  supply_special_weapons_2 addItemCargoGlobal ["V_TacVest_blk",1];

  clearweaponcargoGlobal supply_basic_weapons_3;
  clearmagazinecargoGlobal supply_basic_weapons_3;
  clearitemcargoGlobal supply_basic_weapons_3;

  supply_basic_weapons_3 addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons_3 addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons_3 addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons_3 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons_3 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons_3 additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons_3 additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo_3;
  clearmagazinecargoGlobal supply_ammo_3;
  clearitemcargoGlobal supply_ammo_3;

  supply_ammo_3 addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo_3 addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives_3;
  clearmagazinecargoGlobal supply_explosives_3;
  clearitemcargoGlobal supply_explosives_3;

  supply_explosives_3 addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives_3 addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives_3 addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives_3 addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives_3 additemcargoGlobal ["FirstAidKit",1];
  supply_explosives_3 additemcargoGlobal ["Rangefinder",1];
  supply_explosives_3 additemcargoGlobal ["NVGoggles",1];
  supply_explosives_3 additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers_3;
  clearmagazinecargoGlobal supply_launchers_3;
  clearitemcargoGlobal supply_launchers_3;

  supply_launchers_3 addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers_3 addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers_3 addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades_3;
  clearmagazinecargoGlobal supply_grenades_3;
  clearitemcargoGlobal supply_grenades_3;

  supply_grenades_3 addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades_3 addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades_3 addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades_3 addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades_3 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades_3 addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades_3 addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades_3 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons_3;
  clearmagazinecargoGlobal supply_special_weapons_3;
  clearitemcargoGlobal supply_special_weapons_3;

  supply_special_weapons_3 additemcargoGlobal ["H_Bandanna_surfer",1];
  supply_special_weapons_3 additemcargoGlobal ["H_Booniehat_dgtl",1];
  supply_special_weapons_3 additemcargoGlobal ["H_Shemag_olive",1];
  supply_special_weapons_3 addBackpackCargoGlobal ["B_Carryall_oucamo",1];
  supply_special_weapons_3 addItemCargoGlobal ["V_TacVest_blk",1];

  clearweaponcargoGlobal supply_basic_weapons_4;
  clearmagazinecargoGlobal supply_basic_weapons_4;
  clearitemcargoGlobal supply_basic_weapons_4;

  supply_basic_weapons_4 addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons_4 addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons_4 addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons_4 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons_4 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons_4 additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons_4 additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo_4;
  clearmagazinecargoGlobal supply_ammo_4;
  clearitemcargoGlobal supply_ammo_4;

  supply_ammo_4 addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo_4 addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives_4;
  clearmagazinecargoGlobal supply_explosives_4;
  clearitemcargoGlobal supply_explosives_4;

  supply_explosives_4 addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives_4 addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives_4 addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives_4 addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives_4 additemcargoGlobal ["FirstAidKit",1];
  supply_explosives_4 additemcargoGlobal ["Rangefinder",1];
  supply_explosives_4 additemcargoGlobal ["NVGoggles",1];
  supply_explosives_4 additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers_4;
  clearmagazinecargoGlobal supply_launchers_4;
  clearitemcargoGlobal supply_launchers_4;

  supply_launchers_4 addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers_4 addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers_4 addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades_4;
  clearmagazinecargoGlobal supply_grenades_4;
  clearitemcargoGlobal supply_grenades_4;

  supply_grenades_4 addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades_4 addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades_4 addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades_4 addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades_4 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades_4 addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades_4 addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades_4 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons_4;
  clearmagazinecargoGlobal supply_special_weapons_4;
  clearitemcargoGlobal supply_special_weapons_4;

  supply_special_weapons_4 additemcargoGlobal ["H_Bandanna_surfer",1];

  clearweaponcargoGlobal supply_basic_weapons_5;
  clearmagazinecargoGlobal supply_basic_weapons_5;
  clearitemcargoGlobal supply_basic_weapons_5;

  supply_basic_weapons_5 addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons_5 addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons_5 addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons_5 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons_5 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons_5 additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons_5 additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo_5;
  clearmagazinecargoGlobal supply_ammo_5;
  clearitemcargoGlobal supply_ammo_5;

  supply_ammo_5 addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo_5 addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives_5;
  clearmagazinecargoGlobal supply_explosives_5;
  clearitemcargoGlobal supply_explosives_5;

  supply_explosives_5 addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives_5 addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives_5 addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives_5 addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives_5 additemcargoGlobal ["FirstAidKit",1];
  supply_explosives_5 additemcargoGlobal ["Rangefinder",1];
  supply_explosives_5 additemcargoGlobal ["NVGoggles",1];
  supply_explosives_5 additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers_5;
  clearmagazinecargoGlobal supply_launchers_5;
  clearitemcargoGlobal supply_launchers_5;

  supply_launchers_5 addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers_5 addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers_5 addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades_5;
  clearmagazinecargoGlobal supply_grenades_5;
  clearitemcargoGlobal supply_grenades_5;

  supply_grenades_5 addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades_5 addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades_5 addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades_5 addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades_5 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades_5 addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades_5 addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades_5 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons_5;
  clearmagazinecargoGlobal supply_special_weapons_5;
  clearitemcargoGlobal supply_special_weapons_5;

  supply_special_weapons_5 additemcargoGlobal ["H_Bandanna_surfer",1];
  supply_special_weapons_5 additemcargoGlobal ["H_Booniehat_dgtl",1];
  supply_special_weapons_5 additemcargoGlobal ["H_Shemag_olive",1];
  supply_special_weapons_5 addBackpackCargoGlobal ["B_OutdoorPack_blk",1];
  supply_special_weapons_5 addBackpackCargoGlobal ["B_Carryall_oucamo",1];
  supply_special_weapons_5 addItemCargoGlobal ["V_TacVest_blk",1];

  clearweaponcargoGlobal supply_basic_weapons_6;
  clearmagazinecargoGlobal supply_basic_weapons_6;
  clearitemcargoGlobal supply_basic_weapons_6;

  supply_basic_weapons_6 addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons_6 addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons_6 addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons_6 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons_6 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons_6 additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons_6 additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo_6;
  clearmagazinecargoGlobal supply_ammo_6;
  clearitemcargoGlobal supply_ammo_6;

  supply_ammo_6 addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo_6 addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives_6;
  clearmagazinecargoGlobal supply_explosives_6;
  clearitemcargoGlobal supply_explosives_6;

  supply_explosives_6 addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives_6 addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives_6 addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives_6 addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives_6 additemcargoGlobal ["FirstAidKit",1];
  supply_explosives_6 additemcargoGlobal ["Rangefinder",1];
  supply_explosives_6 additemcargoGlobal ["NVGoggles",1];
  supply_explosives_6 additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers_6;
  clearmagazinecargoGlobal supply_launchers_6;
  clearitemcargoGlobal supply_launchers_6;

  supply_launchers_6 addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers_6 addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers_6 addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades_6;
  clearmagazinecargoGlobal supply_grenades_6;
  clearitemcargoGlobal supply_grenades_6;

  supply_grenades_6 addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades_6 addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades_6 addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades_6 addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades_6 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades_6 addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades_6 addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades_6 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons_6;
  clearmagazinecargoGlobal supply_special_weapons_6;
  clearitemcargoGlobal supply_special_weapons_6;

  supply_special_weapons_6 additemcargoGlobal ["H_Bandanna_surfer",1];
  supply_special_weapons_6 additemcargoGlobal ["H_Booniehat_dgtl",1];
  supply_special_weapons_6 additemcargoGlobal ["H_Shemag_olive",1];
  supply_special_weapons_6 addBackpackCargoGlobal ["B_OutdoorPack_blk",1];
  supply_special_weapons_6 addBackpackCargoGlobal ["B_Carryall_oucamo",1];
  supply_special_weapons_6 addItemCargoGlobal ["V_TacVest_blk",1];

  clearweaponcargoGlobal supply_basic_weapons_7;
  clearmagazinecargoGlobal supply_basic_weapons_7;
  clearitemcargoGlobal supply_basic_weapons_7;

  supply_basic_weapons_7 addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons_7 addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons_7 addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons_7 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons_7 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons_7 additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons_7 additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo_7;
  clearmagazinecargoGlobal supply_ammo_7;
  clearitemcargoGlobal supply_ammo_7;

  supply_ammo_7 addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo_7 addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives_7;
  clearmagazinecargoGlobal supply_explosives_7;
  clearitemcargoGlobal supply_explosives_7;

  supply_explosives_7 addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives_7 addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives_7 addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives_7 addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives_7 additemcargoGlobal ["FirstAidKit",1];
  supply_explosives_7 additemcargoGlobal ["Rangefinder",1];
  supply_explosives_7 additemcargoGlobal ["NVGoggles",1];
  supply_explosives_7 additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers_7;
  clearmagazinecargoGlobal supply_launchers_7;
  clearitemcargoGlobal supply_launchers_7;

  supply_launchers_7 addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers_7 addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers_7 addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades_7;
  clearmagazinecargoGlobal supply_grenades_7;
  clearitemcargoGlobal supply_grenades_7;

  supply_grenades_7 addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades_7 addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades_7 addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades_7 addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades_7 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades_7 addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades_7 addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades_7 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons_7;
  clearmagazinecargoGlobal supply_special_weapons_7;
  clearitemcargoGlobal supply_special_weapons_7;

  supply_special_weapons_7 additemcargoGlobal ["G_Spectacles_Tinted",1];
  supply_special_weapons_7 additemcargoGlobal ["H_Bandanna_surfer",1];
  supply_special_weapons_7 additemcargoGlobal ["H_Booniehat_dgtl",1];
  supply_special_weapons_7 additemcargoGlobal ["H_Shemag_olive",1];
  supply_special_weapons_7 addBackpackCargoGlobal ["B_OutdoorPack_blk",1];
  supply_special_weapons_7 addBackpackCargoGlobal ["B_Carryall_oucamo",1];

  clearweaponcargoGlobal supply_basic_weapons_8;
  clearmagazinecargoGlobal supply_basic_weapons_8;
  clearitemcargoGlobal supply_basic_weapons_8;

  supply_basic_weapons_8 addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons_8 addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons_8 addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons_8 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons_8 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons_8 additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons_8 additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo_8;
  clearmagazinecargoGlobal supply_ammo_8;
  clearitemcargoGlobal supply_ammo_8;

  supply_ammo_8 addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo_8 addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives_8;
  clearmagazinecargoGlobal supply_explosives_8;
  clearitemcargoGlobal supply_explosives_8;

  supply_explosives_8 addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives_8 addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives_8 addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives_8 addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives_8 additemcargoGlobal ["FirstAidKit",1];
  supply_explosives_8 additemcargoGlobal ["Rangefinder",1];
  supply_explosives_8 additemcargoGlobal ["NVGoggles",1];
  supply_explosives_8 additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers_8;
  clearmagazinecargoGlobal supply_launchers_8;
  clearitemcargoGlobal supply_launchers_8;

  supply_launchers_8 addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers_8 addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers_8 addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades_8;
  clearmagazinecargoGlobal supply_grenades_8;
  clearitemcargoGlobal supply_grenades_8;

  supply_grenades_8 addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades_8 addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades_8 addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades_8 addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades_8 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades_8 addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades_8 addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades_8 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons_8;
  clearmagazinecargoGlobal supply_special_weapons_8;
  clearitemcargoGlobal supply_special_weapons_8;

  supply_special_weapons_8 additemcargoGlobal ["G_Spectacles_Tinted",1];
  supply_special_weapons_8 additemcargoGlobal ["H_Bandanna_surfer",1];
  supply_special_weapons_8 additemcargoGlobal ["H_Booniehat_dgtl",1];
  supply_special_weapons_8 additemcargoGlobal ["H_Shemag_olive",1];
  supply_special_weapons_8 addBackpackCargoGlobal ["B_OutdoorPack_blk",1];
  supply_special_weapons_8 addBackpackCargoGlobal ["B_Carryall_oucamo",1];
  supply_special_weapons_8 addItemCargoGlobal ["V_TacVest_blk",1];

  clearweaponcargoGlobal supply_basic_weapons_9;
  clearmagazinecargoGlobal supply_basic_weapons_9;
  clearitemcargoGlobal supply_basic_weapons_9;

  supply_basic_weapons_9 addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons_9 addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons_9 addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons_9 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons_9 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons_9 additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons_9 additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo_9;
  clearmagazinecargoGlobal supply_ammo_9;
  clearitemcargoGlobal supply_ammo_9;

  supply_ammo_9 addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo_9 addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives_9;
  clearmagazinecargoGlobal supply_explosives_9;
  clearitemcargoGlobal supply_explosives_9;

  supply_explosives_9 addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives_9 addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives_9 addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives_9 addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives_9 additemcargoGlobal ["FirstAidKit",1];
  supply_explosives_9 additemcargoGlobal ["Rangefinder",1];
  supply_explosives_9 additemcargoGlobal ["NVGoggles",1];
  supply_explosives_9 additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers_9;
  clearmagazinecargoGlobal supply_launchers_9;
  clearitemcargoGlobal supply_launchers_9;

  supply_launchers_9 addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers_9 addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers_9 addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades_9;
  clearmagazinecargoGlobal supply_grenades_9;
  clearitemcargoGlobal supply_grenades_9;

  supply_grenades_9 addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades_9 addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades_9 addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades_9 addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades_9 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades_9 addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades_9 addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades_9 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons_9;
  clearmagazinecargoGlobal supply_special_weapons_9;
  clearitemcargoGlobal supply_special_weapons_9;

  supply_special_weapons_9 additemcargoGlobal ["G_Spectacles_Tinted",1];
  supply_special_weapons_9 additemcargoGlobal ["H_Bandanna_surfer",1];
  supply_special_weapons_9 additemcargoGlobal ["H_Booniehat_dgtl",1];
  supply_special_weapons_9 additemcargoGlobal ["H_Shemag_olive",1];
  supply_special_weapons_9 addBackpackCargoGlobal ["B_OutdoorPack_blk",1];
  supply_special_weapons_9 addBackpackCargoGlobal ["B_Carryall_oucamo",1];
  supply_special_weapons_9 addItemCargoGlobal ["V_TacVest_blk",1];

  clearweaponcargoGlobal supply_basic_weapons_10;
  clearmagazinecargoGlobal supply_basic_weapons_10;
  clearitemcargoGlobal supply_basic_weapons_10;

  supply_basic_weapons_10 addweaponcargoGlobal ["arifle_MXC_Black_F",1];
  supply_basic_weapons_10 addweaponcargoGlobal ["hgun_Pistol_heavy_02_F",1];
  supply_basic_weapons_10 addmagazinecargoGlobal ["30Rnd_9x21_Mag",6];
  supply_basic_weapons_10 addmagazinecargoGlobal ["30Rnd_65x39_caseless_mag",8];
  supply_basic_weapons_10 addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",4];
  supply_basic_weapons_10 additemcargoGlobal ["optic_Hamr",1];
  supply_basic_weapons_10 additemcargoGlobal ["muzzle_snds_L",1];

  clearweaponcargoGlobal supply_ammo_10;
  clearmagazinecargoGlobal supply_ammo_10;
  clearitemcargoGlobal supply_ammo_10;

  supply_ammo_10 addweaponcargoGlobal ["LMG_Zafir_F",1];
  supply_ammo_10 addmagazinecargoGlobal ["150Rnd_762x51_Box",1];

  clearweaponcargoGlobal supply_explosives_10;
  clearmagazinecargoGlobal supply_explosives_10;
  clearitemcargoGlobal supply_explosives_10;

  supply_explosives_10 addmagazinecargoGlobal ["Chemlight_yellow",4];
  supply_explosives_10 addmagazinecargoGlobal ["Chemlight_blue",5];
  supply_explosives_10 addmagazinecargoGlobal ["Chemlight_red",4];
  supply_explosives_10 addmagazinecargoGlobal ["Chemlight_green",4];
  supply_explosives_10 additemcargoGlobal ["FirstAidKit",1];
  supply_explosives_10 additemcargoGlobal ["Rangefinder",1];
  supply_explosives_10 additemcargoGlobal ["NVGoggles",1];
  supply_explosives_10 additemcargoGlobal ["ItemGPS",1];

  clearweaponcargoGlobal supply_launchers_10;
  clearmagazinecargoGlobal supply_launchers_10;
  clearitemcargoGlobal supply_launchers_10;

  supply_launchers_10 addweaponcargoGlobal ["launch_RPG32_F",1];
  supply_launchers_10 addmagazinecargoGlobal ["RPG32_HE_F",1];
  supply_launchers_10 addmagazinecargoGlobal ["RPG32_F",1];

  clearweaponcargoGlobal supply_grenades_10;
  clearmagazinecargoGlobal supply_grenades_10;
  clearitemcargoGlobal supply_grenades_10;

  supply_grenades_10 addmagazinecargoGlobal ["ATMine_Range_Mag",2];
  supply_grenades_10 addmagazinecargoGlobal ["APERSTripMine_Wire_Mag",1];
  supply_grenades_10 addmagazinecargoGlobal ["SmokeShell",1];
  supply_grenades_10 addmagazinecargoGlobal ["HandGrenade",3];
  supply_grenades_10 addmagazinecargoGlobal ["SatchelCharge_Remote_Mag",1];
  supply_grenades_10 addmagazinecargoGlobal ["MiniGrenade",1];
  supply_grenades_10 addmagazinecargoGlobal ["SmokeShellRed",1];
  supply_grenades_10 addmagazinecargoGlobal ["DemoCharge_Remote_Mag",1];

  clearweaponcargoGlobal supply_special_weapons_10;
  clearmagazinecargoGlobal supply_special_weapons_10;
  clearitemcargoGlobal supply_special_weapons_10;

  supply_special_weapons_10 additemcargoGlobal ["G_Spectacles_Tinted",1];
  supply_special_weapons_10 additemcargoGlobal ["H_Bandanna_surfer",1];
  supply_special_weapons_10 additemcargoGlobal ["H_Booniehat_dgtl",1];
  supply_special_weapons_10 additemcargoGlobal ["H_Shemag_olive",1];
  supply_special_weapons_10 addBackpackCargoGlobal ["B_OutdoorPack_blk",1];
  supply_special_weapons_10 addBackpackCargoGlobal ["B_Carryall_oucamo",1];
  supply_special_weapons_10 addItemCargoGlobal ["V_TacVest_blk",1];


/**
* Loadout for soldiers units
*/

if (!isNil "officer") then {
removeallweapons officer;
removeallassigneditems officer;
removeHeadgear officer;
removeUniform officer;
removeBackpack officer;
removeVest officer;

officer addWeapon "ItemMap";
officer addWeapon "ItemWatch";
officer addWeapon "ItemCompass";
officer addWeapon "ItemGPS";
officer addWeapon "H_Shemag_khk";
officer addWeapon "G_Spectacles";
officer addWeapon "Binocular";
officer addBackpack "B_TacticalPack_blk";
(backpackContainer officer) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",1];
officer addWeapon "arifle_Katiba_GL_F";
removeBackpack officer;
officer addPrimaryWeaponItem "optic_Arco";
officer addBackpack "B_TacticalPack_blk";
(backpackContainer officer) addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",1];
officer addWeapon "hgun_Pistol_heavy_02_F";
removeBackpack officer;
officer addBackpack "B_BergenG";
clearItemCargoGlobal (backpackContainer officer);
clearMagazineCargoGlobal (backpackContainer officer);
clearWeaponCargoGlobal (backpackContainer officer);
(backpackContainer officer) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",4];
officer addVest "V_TacVest_blk";
clearItemCargoGlobal (vestContainer officer);
clearMagazineCargoGlobal (vestContainer officer);
clearWeaponCargoGlobal (vestContainer officer);
(vestContainer officer) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",2];
officer addUniform "U_O_OfficerUniform_ocamo";
clearItemCargoGlobal (uniformContainer officer);
clearMagazineCargoGlobal (uniformContainer officer);
clearWeaponCargoGlobal (uniformContainer officer);
(uniformContainer officer) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",2];
officer selectWeapon (primaryWeapon officer);
};

if (!isNil "officer2") then {
removeallweapons officer2;
removeallassigneditems officer2;
removeHeadgear officer2;
removeUniform officer2;
removeBackpack officer2;
removeVest officer2;

officer2 addWeapon "ItemMap";
officer2 addWeapon "ItemWatch";
officer2 addWeapon "ItemCompass";
officer2 addWeapon "ItemGPS";
officer2 addWeapon "H_Cap_tan_specops_US";
officer2 addWeapon "G_Squares_Tinted";
officer2 addWeapon "Binocular";
officer2 addBackpack "B_TacticalPack_blk";
(backpackContainer officer2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",1];
officer2 addWeapon "arifle_Katiba_GL_F";
removeBackpack officer2;
officer2 addVest "V_BandollierB_cbr";
clearItemCargoGlobal (vestContainer officer2);
clearMagazineCargoGlobal (vestContainer officer2);
clearWeaponCargoGlobal (vestContainer officer2);
(vestContainer officer2) additemcargoGlobal ["optic_Arco",1];
(vestContainer officer2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",4];
(vestContainer officer2) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",5];
officer2 addUniform "U_O_OfficerUniform_ocamo";
clearItemCargoGlobal (uniformContainer officer2);
clearMagazineCargoGlobal (uniformContainer officer2);
clearWeaponCargoGlobal (uniformContainer officer2);
officer2 selectWeapon (primaryWeapon officer2);
};

