/**
* Generated by LEA for Arma 3
* Version: 2.0.17
* Sun Apr 13 12:08:14 CEST 2014
* Mission file name: tvt07_where-is-the-agent-4.Altis
* Mission name: tvt07_where-is-the-agent-4.Altis
* Required mods:
* + ArmA 3
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/


/**
* Loadout for soldiers units
*/

if (player == officer) exitwith {
removeallweapons officer;
removeallassigneditems officer;
removeHeadgear officer;
removeUniform officer;
removeBackpack officer;
removeVest officer;

officer addWeapon "ItemMap";
officer addWeapon "ItemWatch";
officer addWeapon "ItemCompass";
officer addWeapon "ItemGPS";
officer addWeapon "H_Shemag_khk";
officer addWeapon "G_Spectacles";
officer addWeapon "Binocular";
officer addBackpack "B_TacticalPack_blk";
(backpackContainer officer) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",1];
officer addWeapon "arifle_Katiba_GL_F";
removeBackpack officer;
officer addPrimaryWeaponItem "optic_Arco";
officer addBackpack "B_TacticalPack_blk";
(backpackContainer officer) addmagazinecargoGlobal ["6Rnd_45ACP_Cylinder",1];
officer addWeapon "hgun_Pistol_heavy_02_F";
removeBackpack officer;
officer addBackpack "B_BergenG";
clearItemCargoGlobal (backpackContainer officer);
clearMagazineCargoGlobal (backpackContainer officer);
clearWeaponCargoGlobal (backpackContainer officer);
(backpackContainer officer) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",4];
officer addVest "V_TacVest_blk";
clearItemCargoGlobal (vestContainer officer);
clearMagazineCargoGlobal (vestContainer officer);
clearWeaponCargoGlobal (vestContainer officer);
(vestContainer officer) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",2];
officer addUniform "U_O_OfficerUniform_ocamo";
clearItemCargoGlobal (uniformContainer officer);
clearMagazineCargoGlobal (uniformContainer officer);
clearWeaponCargoGlobal (uniformContainer officer);
(uniformContainer officer) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",2];
officer selectWeapon (primaryWeapon officer);
};

if (player == officer2) exitwith {
removeallweapons officer2;
removeallassigneditems officer2;
removeHeadgear officer2;
removeUniform officer2;
removeBackpack officer2;
removeVest officer2;

officer2 addWeapon "ItemMap";
officer2 addWeapon "ItemWatch";
officer2 addWeapon "ItemCompass";
officer2 addWeapon "ItemGPS";
officer2 addWeapon "H_Cap_tan_specops_US";
officer2 addWeapon "G_Squares_Tinted";
officer2 addWeapon "Binocular";
officer2 addBackpack "B_TacticalPack_blk";
(backpackContainer officer2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",1];
officer2 addWeapon "arifle_Katiba_GL_F";
removeBackpack officer2;
officer2 addVest "V_BandollierB_cbr";
clearItemCargoGlobal (vestContainer officer2);
clearMagazineCargoGlobal (vestContainer officer2);
clearWeaponCargoGlobal (vestContainer officer2);
(vestContainer officer2) additemcargoGlobal ["optic_Arco",1];
(vestContainer officer2) addmagazinecargoGlobal ["30Rnd_65x39_caseless_green",4];
(vestContainer officer2) addmagazinecargoGlobal ["1Rnd_HE_Grenade_shell",5];
officer2 addUniform "U_O_OfficerUniform_ocamo";
clearItemCargoGlobal (uniformContainer officer2);
clearMagazineCargoGlobal (uniformContainer officer2);
clearWeaponCargoGlobal (uniformContainer officer2);
officer2 selectWeapon (primaryWeapon officer2);
};

