_x = hacking_time/10;

if (current_frequency == "") exitWith {
	hint format ["Hacking radio tower."];
sleep _x;
hint format ["Hacking radio tower.."];
sleep _x;
hint format ["Hacking radio tower..."];
sleep _x;
hint format ["Hacking radio tower...."];
sleep _x;
hint format ["Hacking radio tower......"];
sleep _x;
hint format ["Hacking radio tower......."];
sleep _x;
hint format ["Hacking radio tower........"];
sleep _x;
hint format ["Hacking radio tower........."];
sleep _x;
hint format ["Hacking radio tower.........."];
sleep _x;
hint format ["Hacking radio tower..........fail"];
sleep 1;
hint format ["We cant get a signal. Sorry."];
};
hint format ["Hacking radio tower."];
sleep _x;
hint format ["Hacking radio tower.."];
sleep _x;
hint format ["Hacking radio tower..."];
sleep _x;
hint format ["Hacking radio tower...."];
sleep _x;
hint format ["Hacking radio tower......"];
sleep _x;
hint format ["Hacking radio tower......."];
sleep _x;
hint format ["Hacking radio tower........"];
sleep _x;
hint format ["Hacking radio tower........."];
sleep _x;
hint format ["Hacking radio tower.........."];
sleep _x;
hint format ["Hacking radio tower..........done"];
sleep 1;
hint format ["Government sides last used frequency was %1",current_frequency];