//leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.
enableSaving [false, false];
//[] execVM "taw_vd\init.sqf";
//[] exec "countdown.sqf"; // this line in your init.sqf
//[] execVM "uniform_management\client.sqf";  // uniform management
[] execVM "taliban_killings\killings.sqf";  // taliban death count
waituntil {!(isnil "bis_fnc_init")};
waituntil {(alive player)};
enableRadio false;
seitenwechsel = false;
publicVariable "seitenwechsel";
firstspawn = false;
publicVariable "firstspawn";
//hintsilent format ["init complete"];